### ISSUE TITLE
Timezone mismatch from PD to gcal or vice versa

### ISSUE THREAD

**Issue by spaghetti-** [corsc/pagerduty-gcal#1]
I believe PD schedules are imported in UTC but Gcal tzs are parsed statically as `00:00:00Z` which causes some issues with morning and afternoon shifts and associated conflicts.

Lifu has a patch for this but I'm just posting it here for tracking.

**Comment by wulifu2hao** [comment]
Thanks Alex, the fix I have is a bit ugly (just subtract 8 hours when its full day event). Maybe Corey can help come up with a better solution

**Comment by corsc** [comment]
Do you happen to a have a test that proves it?

It might be time for me to add some ability to mock the external calls :)

**Comment by wulifu2hao** [comment]
Hi Corey, I don’t have at the moment. We discovered it when doing the
scheduling for the first time: it says Alex has a conflict (morning shift)
on some day (e.g Feb 7), but Alex knows that he is free on that day, but is
not free one day before (Feb 6). So I suspect its due to time zone so I
subtract 8 hours from the whole day event on Feb 6 and the conflict goes
away

**Comment by corsc** [comment]
No worries.  Thanks for the report
